// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SysAgentV2.Data;

#nullable disable

namespace SysAgentV2.Migrations
{
    [DbContext(typeof(SysDbContext))]
    [Migration("20250526201724_ImplementMigrations")]
    partial class ImplementMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("SysAgentV2.Models.AgentExecutionStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("edited_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("t_status_agent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 26, 20, 17, 24, 280, DateTimeKind.Utc).AddTicks(7069),
                            Status = "STOPPED"
                        });
                });

            modelBuilder.Entity("SysAgentV2.Models.AgentHealthStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("edited_at");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("health_status");

                    b.HasKey("Id");

                    b.ToTable("t_status_health");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 26, 20, 17, 24, 281, DateTimeKind.Utc).AddTicks(1853),
                            HealthStatus = "DISABLED"
                        });
                });

            modelBuilder.Entity("SysAgentV2.Models.AgentScripFile", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsChained")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_chained");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tag");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Uuid");

                    b.ToTable("t_repo_scripts_file");
                });

            modelBuilder.Entity("SysAgentV2.Models.AgentScriptCmd", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsChained")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_chained");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("script");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tag");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Uuid");

                    b.ToTable("t_repo_scripts_cmd");
                });

            modelBuilder.Entity("SysAgentV2.Models.CollectMetrics", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("JsonResult")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("json_result");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Uuid");

                    b.ToTable("t_collect_metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
